sudo: no
language: python
cache: pip
matrix:
  include:
    - python: "2.7"
      env: TOXENV=docs
    - python: "2.7"
      env: TOXENV=py27-1.6
    - python: "3.3"
      env: TOXENV=py33-1.6
    - python: "2.7"
      env: TOXENV=py27-1.7
    - python: "3.4"
      env: TOXENV=py34-1.7
    - python: "2.7"
      env: TOXENV=py27-1.8
    - python: "3.5"
      env: TOXENV=py35-1.8
    - python: "2.7"
      env: TOXENV=py27-1.9
    - python: "3.5"
      env: TOXENV=py35-1.9
    - python: "2.7"
      env: TOXENV=py27-1.10
    - python: "3.5"
      env: TOXENV=py35-1.10
    - python: "2.7"
      env: TOXENV=py27-1.11
    - python: "3.6"
      env: TOXENV=py36-1.11
    - python: "3.6"
      env: TOXENV=py36-master
  allow_failures:
    - env: TOXENV=py27-1.8
    - env: TOXENV=py35-1.8
    - env: TOXENV=py27-1.9
    - env: TOXENV=py35-1.9
    - env: TOXENV=py27-1.10
    - env: TOXENV=py35-1.10
    - env: TOXENV=py27-1.11
    - env: TOXENV=py36-1.11
    - env: TOXENV=py36-master
install:
  - pip install coveralls tox
script:
  - tox
after_success: coveralls
